{% set name = "aioitertools" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2a9055b4fbb7705f561b9d86053e8af5d10cc845d22c32008c43490b2d8dd6b

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - flit-core >=3.8,<4
  run:
    - python
    - typing_extensions >=4.0  # [py<310]

test:
  imports:
    - aioitertools
    - aioitertools.asyncio
    - aioitertools.helpers
    - aioitertools.more_itertools
  requires:
    - pip
  commands:
    - pip check


about:
  home: https://aioitertools.omnilib.dev
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio version of the standard multiprocessing module
  description: |
    Implementation of itertools, builtins, and more for AsyncIO and mixed-type
    iterables.
  doc_url: https://aioitertools.omnilib.dev
  dev_url: https://github.com/jreese/aioitertools

extra:
  recipe-maintainers:
    - nehaljwani
