{% set name = "aioitertools" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3684a9e5626664169ee31bc6e40d30d1ad86d9a1832d251652fda2cf3e3e74ae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - aioitertools
    - aioitertools.tests

about:
  home: https://github.com/jreese/aioitertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio version of the standard multiprocessing module
  description: |
    Implementation of itertools, builtins, and more for AsyncIO and mixed-type
    iterables.
  doc_url: https://github.com/jreese/aioitertools
  dev_url: https://github.com/jreese/aioitertools

extra:
  recipe-maintainers:
    - nehaljwani
